### ISSUE TITLE
Sign in Websocket API

### ISSUE THREAD

**Issue by CryptoArbitrage9** [hotbitex/hotbit.io-api-docs#5]
Good day!
 
Didn't find any information in your documentation about what parameters should be contained in "Sign" for Websocket for User Verification?
 
Request example:
{
    "method":"server.auth",
    "params":[api_key,sign],
    "id":100
}

**Comment by dhudd3** [comment]
try reading https://github.com/hotbitex/hotbit.io-api-docs sign from what i understand is just the signed value of the request string hope that helps

**Comment by CryptoArbitrage9** [comment]
> try reading https://github.com/hotbitex/hotbit.io-api-docs sign from what i understand is just the signed value of the request string hope that helps

The fact is that the description is only for Rest Api, and for Websockets it is not known what parameters should be included in the string ...

**Comment by CryptoArbitrage9** [comment]
The solution has been found, maybe someone will be useful:
sign = MD5($"api_key={Api_Key}&secret_key={Api_Secret}")
Request:
{"method":"server.auth","params":["api_key","sign"],"id":100}

**Comment by MWagihM** [comment]
Where can I find my api & secret keys? @CryptoArbitrage9
